services:
  - type: worker
    name: ghoghnoos-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: OPENAI_API_KEY
        sync: false

      - key: ADMIN_NAME
        sync: false

      - key: ADMIN_PHONE
        sync: false

      - key: CHANNEL_USERNAME
        sync: false
